#!/usr/bin/env bash
# _scaffold-lib.sh
# Shared helpers for the swift-modularization CLAUDE.md scaffolders.
# Not meant to be run directly — sourced by scaffold-package-claude-md.sh
# and scaffold-target-claude-md.sh.
#
# The scaffolders write a managed, idempotent block into a CLAUDE.md file. The
# block is delimited by stable markers so re-running replaces ONLY the managed
# content and preserves anything hand-written outside the markers.

set -euo pipefail

# Resolve this library's own directory so we can find ../templates regardless
# of the caller's working directory.
SCAFFOLD_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$SCAFFOLD_LIB_DIR/../templates"

# render_template <relative-template-path> <heading>
# Prints the heading followed by the named template's body, substituting the
# literal token `<Domain>`/`Foo` left as-is (they are intentional placeholders
# the author fills in). Errors if the template is missing.
render_template() {
  local tpl="$TEMPLATES_DIR/$1"
  local heading="$2"
  if [ ! -f "$tpl" ]; then
    echo "error: missing template: $tpl" >&2
    exit 1
  fi
  printf '# %s\n\n' "$heading"
  cat "$tpl"
}

# write_managed_block <file> <marker-key> <content>
# Idempotently writes <content> into <file> between markers keyed by
# <marker-key>. On first run the block is appended (creating the file and
# parent dirs if needed). On re-run the existing block is replaced in place;
# content outside the markers is untouched.
write_managed_block() {
  local file="$1"
  local key="$2"
  local content="$3"

  local start="<!-- swift-modularization:managed START $key -->"
  local end="<!-- swift-modularization:managed END $key -->"

  mkdir -p "$(dirname "$file")"

  local block
  block="$start
<!-- Generated by the swift-modularization scaffolder. Edit OUTSIDE these markers; -->
<!-- content between them is overwritten on re-run. -->
$content
$end"

  if [ -f "$file" ] && grep -qF "$start" "$file"; then
    # Replace existing managed block, preserve everything else.
    # The replacement is read from a file (not an awk -v var) so multi-line
    # content works on both BSD/macOS and GNU awk.
    local tmp blockfile
    tmp="$(mktemp)"
    blockfile="$(mktemp)"
    printf '%s\n' "$block" > "$blockfile"
    awk -v s="$start" -v e="$end" -v bf="$blockfile" '
      index($0, s) { while ((getline line < bf) > 0) print line; close(bf); skip = 1; next }
      skip && index($0, e) { skip = 0; next }
      !skip { print }
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
    rm -f "$blockfile"
    echo "  ↻ updated managed block ($key) in $file"
  else
    # Append a fresh block (with a leading blank line if the file has content).
    if [ -s "$file" ]; then
      printf '\n%s\n' "$block" >> "$file"
    else
      printf '%s\n' "$block" > "$file"
    fi
    echo "  ✓ wrote managed block ($key) to $file"
  fi
}
